"""
Shopify Navigation Menu Synchronizer & Liquid Exporter
Synchronizes the hierarchical 3-tier catalog menu to Shopify Online Store Navigation (ADR 0022).
Provides programmatic GraphQL menu updates or exports theme Liquid snippets.
Pure functions only, zero classes (ADR 0005).
"""
import os
import sys
import json
import argparse
from typing import Dict, Any, List, Optional

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _ROOT not in sys.path:
    sys.path.insert(0, _ROOT)

from storage.shopify_auth import execute_shopify_graphql
from storage.logger import init_logger, log_info, log_success, log_warning, log_error

DEFAULT_MANIFEST_PATH = os.path.join(_ROOT, "config", "shopify_navigation_manifest.json")


def load_navigation_manifest(path: str = DEFAULT_MANIFEST_PATH) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def export_as_liquid_nav(manifest: Dict[str, Any]) -> str:
    """Generates a clean Liquid navigation snippet for theme sidebars."""
    lines = [
        "<!-- Auto-generated by scripts/shopify_menu_sync.py (ADR 0022) -->",
        "<nav class=\"luxury-sidebar-nav\" aria-label=\"Main Navigation\">",
        "  <ul class=\"nav-dept-list space-y-4\">"
    ]
    for dept in manifest.get("navigation", []):
        d_title = dept.get("title")
        d_url = dept.get("url", "#")
        lines.append("    <li class=\"dept-item group\">")
        lines.append("      <div class=\"dept-header flex items-center justify-between font-semibold tracking-wider uppercase py-2 cursor-pointer\">")
        lines.append(f"        <a href=\"{d_url}\" class=\"hover:text-amber-500 transition-colors\">{d_title}</a>")
        if dept.get("items"):
            lines.append("        <span class=\"dept-toggle text-xs text-neutral-400 group-hover:text-white\">+</span>")
        lines.append("      </div>")
        
        if dept.get("items"):
            lines.append("      <ul class=\"category-list pl-3 space-y-2 border-l border-neutral-800 ml-1 mt-1\">")
            for cat in dept["items"]:
                c_title = cat.get("title")
                c_url = cat.get("url", "#")
                lines.append("        <li class=\"cat-item\">")
                lines.append(f"          <a href=\"{c_url}\" class=\"block text-sm font-medium text-neutral-300 hover:text-white py-1\">{c_title}</a>")
                
                if cat.get("items"):
                    lines.append("          <ul class=\"brand-list pl-3 space-y-1 border-l border-neutral-900 ml-1 mt-0.5\">")
                    for brand in cat["items"]:
                        b_title = brand.get("title")
                        b_url = brand.get("url", "#")
                        lines.append(f"            <li><a href=\"{b_url}\" class=\"block text-xs text-neutral-400 hover:text-amber-400 py-0.5 transition-colors\">{b_title}</a></li>")
                    lines.append("          </ul>")
                lines.append("        </li>")
            lines.append("      </ul>")
        lines.append("    </li>")
    lines.append("  </ul>")
    lines.append("</nav>")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Synchronize or export Shopify navigation menu.")
    parser.add_argument("--export-liquid", action="store_true", help="Export menu as Liquid snippet")
    parser.add_argument("--manifest", default=DEFAULT_MANIFEST_PATH, help="Path to navigation manifest")
    args = parser.parse_args()

    manifest = load_navigation_manifest(args.manifest)
    print(f"Loaded manifest with {len(manifest.get('navigation', []))} top-level departments.")

    if args.export_liquid:
        liquid_code = export_as_liquid_nav(manifest)
        out_path = os.path.join(_ROOT, "theme", "snippets", "luxury_sidebar_navigation.liquid")
        os.makedirs(os.path.dirname(out_path), exist_ok=True)
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(liquid_code)
        print(f"Exported Liquid snippet to: {out_path}")


if __name__ == "__main__":
    main()
